# Generated by Django 6.0 on 2025-12-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crm_group_id', models.IntegerField(unique=True)),
                ('branch_ids', models.JSONField()),
                ('teacher_ids', models.JSONField()),
                ('name', models.CharField(max_length=500)),
                ('level_id', models.IntegerField()),
                ('status_id', models.IntegerField()),
                ('company_id', models.IntegerField(null=True)),
                ('streaming_id', models.IntegerField(null=True)),
                ('limit', models.IntegerField()),
                ('note', models.TextField(null=True)),
                ('b_date', models.CharField(max_length=10, null=True)),
                ('e_date', models.CharField(max_length=10, null=True)),
                ('created_at', models.CharField(max_length=20, null=True)),
                ('updated_at', models.CharField(max_length=20, null=True)),
                ('custom_aerodromnaya', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_crm_id', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_crm_id', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tutor_crm_id', models.CharField(max_length=255, null=True, unique=True)),
                ('tutor_name', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('is_senior', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('branch_ids', models.JSONField(null=True)),
                ('dob', models.CharField(max_length=10, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('streaming_id', models.IntegerField(null=True)),
                ('note', models.TextField(null=True)),
                ('e_date', models.CharField(max_length=10, null=True)),
                ('avatar_url', models.CharField(max_length=500, null=True)),
                ('phone', models.JSONField(null=True)),
                ('email', models.JSONField(null=True)),
                ('web', models.JSONField(null=True)),
                ('addr', models.JSONField(null=True)),
                ('teacher_to_skill', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_crm_id', models.IntegerField(unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app_resumes.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='groups', to='app_resumes.tutorprofile'),
        ),
    ]
